TOP = ../../../..
include $(TOP)/configs/current

LIBNAME = rempipe

C_SOURCES = \
	graw_encode.c \
	graw_context.c \
        rempipe_screen.c \
        graw_pipe_winsys.c

include ../../Makefile.template
